<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span><ul class="toc-item"><li><span><a href="#Оценка-модели-до-преобразований" data-toc-modified-id="Оценка-модели-до-преобразований-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Оценка модели до преобразований</a></span></li><li><span><a href="#Применение-алгоритма-и-оценка-после-преобразований" data-toc-modified-id="Применение-алгоритма-и-оценка-после-преобразований-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Применение алгоритма и оценка после преобразований</a></span></li></ul></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [20]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [21]:
df = pd.read_csv('/datasets/insurance.csv')
df.info()
display(df.head())
display(df.corr())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

Пол   Возраст  Зарплата  Члены семьи  \
Пол                1.000000  0.002074  0.014910    -0.008991   
Возраст            0.002074  1.000000 -0.019093    -0.006692   
Зарплата           0.014910 -0.019093  1.000000    -0.030296   
Члены семьи       -0.008991 -0.006692 -0.030296     1.000000   
Страховые выплаты  0.010140  0.651030 -0.014963    -0.036290   

                   Страховые выплаты  
Пол                         0.010140  
Возраст                     0.651030  
Зарплата                   -0.014963  
Члены семьи                -0.036290  
Страховые выплаты           1.000000

**Вывод**   
- датасет состоит из 5000 наблюдений.
- пропусков нет.
- названия столбцов нужно переименовать для дальнейшего анализа.
- типы данных стоит изменить для возраста и зарплаты на integer, так как они содержат только целочисленные значения.
- мультиколлинеарность факторов не обнаружена.

In [22]:
df.columns = ['gender', 'age', 'salary', 'family_members', 'insurance_cases']
df['age'] = df['age'].astype('int')
df['salary'] = df['salary'].astype('int')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   gender           5000 non-null   int64
 1   age              5000 non-null   int64
 2   salary           5000 non-null   int64
 3   family_members   5000 non-null   int64
 4   insurance_cases  5000 non-null   int64
dtypes: int64(5)
memory usage: 195.4 KB


## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** Не изменится

**Обоснование:**   
Докажем, что домножение на обратимую матрицу не влияет на получение прогнозных значений:    
$$    
a = Xw = X (X^T X)^{-1} X^T y
$$
Домножим матрицу факторов на матрицу P:
$$
a = XP ((XP)^T XP)^{-1} (XP)^T y
$$
*По свойтву умножения матриц:*
$$
(AB)^T = B^T A^T
$$
$$
(AB)^{-1} = B^{-1} A^{-1}
$$
$$
(A^T)^{-1} = (A^{-1})^T
$$
=> 
$$
a = X P ((P^T (X^T X)) P)^{-1} P^T X^T y
$$
$$
a = X P P^{-1} (P^T (X^T X))^{-1} P^T X^T y
$$
$$
a = X P P^{-1} (X^T X)^{-1} (P^T)^{-1} P^T X^T y
$$

Поскольку матрица P обратима: 
$$
P P^{-1} = E
$$
$$
(P^T)^{-1} P^T = E
$$
тогда:   
$$
a = X (X^T X)^{-1} X^T y
$$
**ч.т.д.**

## Алгоритм преобразования

**Алгоритм**

1. Определение размерности матрицы факторов X.
2. Создание обратимой матрицы P в соответствии с размерностью из п.1
3. Нахождение обратной матрицы $P^{-1}$
4. Домножение матрицы X на $P^{-1}$

**Обоснование**

Данный алгоритм шифрования не повлияет на качество оценки, так как обратная матрица от обратимой является также обратимой => это преобразование, аналогичное пункту 2.

## Проверка алгоритма

Подготовим датасет

In [23]:
features = df.drop(['insurance_cases'], axis=1).values
X = np.concatenate((np.ones((features.shape[0], 1)), features), axis=1)
y = df['insurance_cases'].values

### Оценка модели до преобразований

Разобьем датасет на выборки и оценим модель с помощью линейной регрессии

In [24]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.25, random_state=12345)
model = LinearRegression()
model.fit(X_train, y_train)
predicted = model.predict(X_valid)
r2 = r2_score(y_valid, predicted)
print(f'R2: {r2:.2f}')

R2: 0.44


**Вывод**   
Оценка модели путем коэффициента детерминации составила 0.44

### Применение алгоритма и оценка после преобразований

In [25]:
def crypto(X):
    N = X.shape[1]
    #если определитель матрицы будет равен 0, т.е. матрица не обратима, создастся новая
    P = np.random.random((N, N))
    while np.linalg.det == 0:
        P = np.random.random((N, N))
    P_inv = np.linalg.inv(P)
    X = X @ P_inv
    return X

In [26]:
#проверим шифровку факторов
print('До шифровки')
print(X)
X = crypto(X)
print()
print('После')
print(X)

До шифровки
[[1.00e+00 1.00e+00 4.10e+01 4.96e+04 1.00e+00]
 [1.00e+00 0.00e+00 4.60e+01 3.80e+04 1.00e+00]
 [1.00e+00 0.00e+00 2.90e+01 2.10e+04 0.00e+00]
 ...
 [1.00e+00 0.00e+00 2.00e+01 3.39e+04 2.00e+00]
 [1.00e+00 1.00e+00 2.20e+01 3.27e+04 3.00e+00]
 [1.00e+00 1.00e+00 2.80e+01 4.06e+04 1.00e+00]]

После
[[-395071.62467857 -605245.91798506 -724016.56582819 1278765.86848914
   531386.60028974]
 [-302555.14216397 -463536.42329873 -554564.54105772  979400.52484938
   407004.656574  ]
 [-167153.0397591  -256100.5939744  -306408.99798392  541121.56583363
   224874.65612828]
 ...
 [-270068.62125234 -413732.50742885 -494882.11896117  874110.46337364
   363224.92178226]
 [-260515.84835102 -399095.2801673  -477382.6501595   843192.49521519
   350380.33702559]
 [-323422.61626982 -495472.56806995 -592675.40937111 1046820.43256341
   434995.49783393]]


In [27]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.25, random_state=12345)
model = LinearRegression()
model.fit(X_train, y_train)
predicted = model.predict(X_valid)
r2 = r2_score(y_valid, predicted)
print(f'R2: {r2:.2f}')

R2: 0.44


**Вывод**   
Качество модели не изменилось - ч.т.д.

## Чек-лист проверки

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [x]  Весь код выполняется без ошибок
- [x]  Ячейки с кодом расположены в порядке исполнения
- [x]  Выполнен шаг 1: данные загружены
- [x]  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [x]  Указан правильный вариант ответа
    - [x]  Вариант обоснован
- [x]  Выполнен шаг 3: предложен алгоритм преобразования
    - [x]  Алгоритм описан
    - [x]  Алгоритм обоснован
- [x]  Выполнен шаг 4: алгоритм проверен
    - [x]  Алгоритм реализован
    - [x]  Проведено сравнение качества моделей до и после преобразования